# Generated by Django 2.0.4 on 2018-09-06 16:20

import campaign.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True)),
                ('image', campaign.fields.ThumbnailImageField(blank=True, null=True, upload_to='with_us/photo/%Y/%m')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
