# Generated by Django 2.0.4 on 2018-07-19 05:25

from django.db import migrations, models
import product.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', product.fields.ThumbnailImageField(upload_to='product/box/%Y/%m')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('인기순', '인기순'), ('최근등록순', '최근등록순'), ('판매인기순', '판매인기순'), ('낮은가격순', '낮은가격순'), ('높은가격순', '높은가격순'), ('상품평많은순', '상품평많은순')], max_length=100)),
                ('g_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', product.fields.ThumbnailImageField(upload_to='product/goods/%Y/%m')),
                ('content', models.TextField()),
            ],
        ),
    ]
