# Generated by Django 2.0.4 on 2018-08-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.CharField(choices=[('의류', '의류'), ('가방', '가방'), ('악세사리', '악세사리'), ('폰케이스', '폰케이스'), ('문구', '문구'), ('책', '책')], max_length=100),
        ),
    ]
