# Generated by Django 2.0.4 on 2018-08-17 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10, null=True)),
                ('birth', models.CharField(help_text='주민등록번호 앞자리를 입력해주세요.', max_length=6, null=True)),
                ('phone', models.CharField(help_text="'-'를 제외한 휴대폰번호 11자리를 입력해 주세요.", max_length=11, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
