# Generated by Django 2.0.4 on 2018-09-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', '남자'), ('W', '여자')], default='M', max_length=10, null=True),
        ),
    ]
