# Generated by Django 2.0.4 on 2018-06-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_qaa_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaa',
            name='password',
            field=models.CharField(max_length=50, null=True, verbose_name='PASSWORD'),
        ),
    ]
