# Generated by Django 2.0.4 on 2018-06-13 04:02

from django.db import migrations
import femiLetter.fields


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_qaa_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaa',
            name='image',
            field=femiLetter.fields.ThumbnailImageField(null=True, upload_to='photo/%Y/%m'),
        ),
    ]
