# Generated by Django 2.0.4 on 2018-06-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_qaa_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qaa',
            name='author',
            field=models.CharField(max_length=100, verbose_name='NAME'),
        ),
    ]
