# Generated by Django 2.0.4 on 2018-06-13 07:32

from django.db import migrations
import femiLetter.fields


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_auto_20180613_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qaa',
            name='image',
            field=femiLetter.fields.ThumbnailImageField(null=True, upload_to=''),
        ),
    ]
