# Generated by Django 2.0.4 on 2018-06-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_auto_20180613_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qaa',
            name='owner',
        ),
    ]
