# Generated by Django 2.0.4 on 2018-06-13 10:19

from django.db import migrations
import femiLetter.fields


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_remove_qaa_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qaa',
            name='image',
            field=femiLetter.fields.ThumbnailImageField(null=True, upload_to='user_photo/%Y/%m'),
        ),
    ]
