# Generated by Django 2.0.4 on 2018-06-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_auto_20180613_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='author',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='qaa',
            name='view_count',
        ),
    ]
