# Generated by Django 2.0.4 on 2018-06-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_auto_20180613_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qaa',
            name='title',
            field=models.CharField(blank=True, choices=[('1', '선택'), ('2', '배송관련문의'), ('3', '상품문의'), ('4', '배송 후 교환반품'), ('5', '입금확인'), ('6', '배송전 주면변경 및 취소'), ('7', '기타')], default='1', max_length=100, verbose_name='TITLE'),
        ),
    ]
