# Generated by Django 2.0.4 on 2018-09-03 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0020_auto_20180702_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qaa',
            options={'ordering': ('-create_date',), 'verbose_name': 'Q&A', 'verbose_name_plural': 'Q&A'},
        ),
    ]
