# Generated by Django 2.0.4 on 2018-06-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femiLetter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memos',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='memos',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
