# Generated by Django 2.0.4 on 2018-06-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femiLetter', '0003_memos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memos',
            name='bad_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='memos',
            name='good_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='memos',
            name='view_count',
            field=models.IntegerField(null=True),
        ),
    ]
