# Generated by Django 2.0.4 on 2018-06-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femiLetter', '0004_auto_20180612_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memos',
            name='bad_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memos',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='memos',
            name='good_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memos',
            name='view_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
