# Generated by Django 2.0.4 on 2018-06-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femiLetter', '0005_auto_20180613_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memos',
            name='title',
            field=models.CharField(choices=[('사람', '사람'), ('#미투', '#미투'), ('이런 날엔 이런 위로', '이런 날엔 이런 위로')], max_length=250),
        ),
    ]
