# Generated by Django 2.0.4 on 2018-08-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femiLetter', '0008_remove_memos_bad_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memos',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
