# Generated by Django 2.0.4 on 2018-07-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('기사', '기사'), ('칼럼', '칼럼'), ('안내', '안내')], default='1', max_length=100, verbose_name='TITLE')),
                ('content', models.TextField(verbose_name='CONTENT')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
            ],
            options={
                'verbose_name': 'notice',
                'verbose_name_plural': 'notice',
                'ordering': ('-create_date',),
            },
        ),
    ]
